### PR TITLE
Adds internationalization to the admin/sparql-query page

### PR DESCRIPTION
**Pull request by awoods**
Partial resolution of: https://jira.lyrasis.org/browse/VIVO-1873

# What does this pull request do?
Add i18n to admin/sparql-query page

# How should this be tested?
- Configure VIVO for multiple languages
- Log into VIVO as admin
- Navigate to siteAdmin >> SPARQL query
- Inspect the following elements for proper i18n translation (note: these are all still English until other translations are available)
   - Page title
   - Page heading
   - Section headings
   - Comment in sample query
- Change language context, and view correct translation (see note above regarding available translations)

# Interested parties
@VIVO-project/vivo-committers

### CODE REVIEW

**Comment by gneissone** [comment]
Can Vitro still be deployed without including Vitro-languages? If so, the language strings should also be added to https://github.com/vivo-project/Vitro/blob/master/webapp/src/main/webapp/i18n/all.properties.

**Comment by awoods** [comment]
@gneissone : Good question. I just tested the `i18n` branch(es) with no languages configured. It appears to work. That is due to the fact that `en_US` is auto-selected if no languages are selected:
- https://github.com/vivo-project/Vitro/commit/413184dad6ea9cc16c1a2cb89ad7b2ed60a094ea#diff-4512a71443070a7312a44c5128c8afb2R189

So I went ahead and tested again after deleting the "all.properties" file:
https://github.com/vivo-project/Vitro/blob/master/webapp/src/main/webapp/i18n/all.properties

Success.

I think we can remove "all.properties" in the `sprint-i18n` branch.

**Comment by gneissone** [comment]
@awoods How do you want to approach supporting the changes merged to master via https://github.com/vivo-project/Vitro/pull/164 ?

**Comment by awoods** [comment]
@gneissone : there is no merge conflict... does anything need to change in this PR?

**Comment by gneissone** [comment]
Perhaps not technically, but there would be a regression in i18n functionality on the page because English is hard-coded into the form here: https://github.com/vivo-project/Vitro/pull/164/files#diff-1dfcb1c02e96af4babf9eeb1e255114fR32

**Comment by awoods** [comment]
@gneissone : if we can update the `sprint-i18n` branches with `master`, then I can update this PR to include the addition you referenced.
See: https://github.com/vivo-project/Vitro/pull/166

**Comment by gneissone** [comment]
@awoods Looks like master has been merged into the i18n sprint branch. Can this PR be updated to include i18n support for this line? https://github.com/vivo-project/Vitro/blob/sprint-i18n/webapp/src/main/webapp/templates/freemarker/body/admin/admin-sparqlQueryForm.ftl#L32

**Comment by awoods** [comment]
@gneissone : This (and the associated: https://github.com/vivo-project/Vitro-languages/pull/22) have been updated.

**Comment by awoods** [comment]
@gneissone : PRs have been updated.

**Comment by awoods** [comment]
@vivo-project/vivo-committers : next reviewer can merge.

**Pull request merged**
