### PR TITLE
Enable TinyMCE for fixed html pages

### PR DESCRIPTION
**Pull request by litvinovg**
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3963)**
[VIVO PR](https://github.com/vivo-project/VIVO/pull/3971)

# What does this pull request do?
Enables TinyMCE editor for Fixed HTML field.

# How should this be tested?
- Create/Edit Fixed html pages, check result

# Additional information
Stacked on top of https://github.com/vivo-project/Vitro/pull/452

# Interested parties
@VIVO-project/vivo-committers

### CODE REVIEW

**Review by chenejac — CHANGES_REQUESTED** [review]
@litvinovg thanks for this contribution.

This is working only in the isolated Vitro instance. 
There is a pageManagement--customDataScript.ftl in VIVO, please apply the similar changes there.

**Review by chenejac — DISMISSED** [review]
@litvinovg I have tested this, it is working as expected. I have posted one comment in the VIVO PR, but it will be resolved in the separate PR. I have review the code only of the second commit, and don't have any suggestion for improvement.

**Comment by milospp** [comment]
@litvinovg When I create a new fixed HTML content I see a basic text editor until I save and refresh the page, only then (when editing) rich text editor is shown.

image

**Comment by litvinovg** [comment]
@milospp I added fixes for the issue. Could you test it once again?

**Comment by milospp** [comment]
> @milospp I added fixes for the issue. Could you test it once again?

I tested and it works fine

**Review by milospp — APPROVED** [review]

**Review by chenejac — APPROVED** [review]
@litvinovg works for me

**Pull request merged**
