### PR TITLE
Added action and resourceAPI to data property version

### PR DESCRIPTION
**Pull request by bkampe**
**Added action and resourceAPI to data property "version" to store version number**
* * *

# What does this pull request do?
To store a version number with action and resourceAPI I extended vitro-dynamic-api#version with both domains

# What's new?
Additionally some other properties with multible domains were corrected from intersection of the classes to a union of the classes

Example:
    <owl:DatatypeProperty rdf:about="https://vivoweb.org/ontology/vitro-dynamic-api#version">
        <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#FunctionalProperty"/>
        <rdfs:domain>
            <owl:Class>
                <owl:unionOf rdf:parseType="Collection">
                    <owl:Class rdf:about="https://vivoweb.org/ontology/vitro-dynamic-api#api"/>
                    <owl:Class rdf:about="https://vivoweb.org/ontology/vitro-dynamic-api#action"/>
                    <owl:Class rdf:about="https://vivoweb.org/ontology/vitro-dynamic-api#resourceAPI"/>
                </owl:unionOf>
            </owl:Class>
        </rdfs:domain>
        <rdfs:domain rdf:resource="https://vivoweb.org/ontology/vitro-dynamic-api#api"/>
        <rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#string"/>
        <rdfs:label xml:lang="en-US">version</rdfs:label>
    </owl:DatatypeProperty>

# Interested parties
@litvinovg @chenejac

### CODE REVIEW

**Review by brianjlowe — CHANGES_REQUESTED** [review]
The general idea of using unionOf is right here, but it looks like something went funny with the repeated rdfs:domains.  All you need is one rdfs:domain triple and a collection of class URIs in the unionOf.  There are some examples in RDF/XML syntax in the main VIVO ontology, e.g.:

<rdfs:domain>
  <owl:Class>
    <owl:unionOf rdf:parseType="Collection">
      <rdf:Description rdf:about="http://purl.obolibrary.org/obo/ERO_0000004"/>
      <rdf:Description rdf:about="http://purl.obolibrary.org/obo/ERO_0000006"/>
      <rdf:Description rdf:about="http://purl.obolibrary.org/obo/ERO_0000071"/>
      <rdf:Description rdf:about="http://purl.obolibrary.org/obo/ERO_0001716"/>
    </owl:unionOf>
  </owl:Class>
</rdfs:domain>

If you replace the lines '<rdfs:domain rdf:resource="X"/>' inside the unionOf with '<rdf:Description rdfs:about="X"/>', then it looks like this will be in good shape.

**Comment by bkampe** [comment]
@brianjlowe That was a copy and paste error. I have corrected it.

**Review by brianjlowe — CHANGES_REQUESTED** [review]
Looks like some of the rdf:about attributes ended up with double equals signs (rdf:about==)

**Comment by bkampe** [comment]
Copy and past part 2 :(
Sorry, no code inspection for owl in my IDE. I should have noticed that myself.

**Review by chenejac — APPROVED** [review]
looks ok for me

**Pull request merged**
