### PR TITLE
Upgrade Jena to 3.11.0

### PR DESCRIPTION
**Pull request by grahamtriggs**
**[VIVO-1693](https://jira.duraspace.org/browse/VIVO-1693)**:

* Other Relevant Links (Mailing list discussion, related pull requests, etc.)

# What does this pull request do?
Upgrades Vitro to Jena 3.11.0. Also updates commons-fileupload to 1.4, to match the version depended on by Jena.

# What's new?
Improves efficiency of SDB queries that involve OPTIONAL / MINUS.

# How should this be tested?
Only a couple of low-level classes have been updated for changes to the Jena interfaces. No functional changes are made in the code.

Test all operations of Vitro / VIVO - everything should work exactly as it did prior to the upgrade.

To test OPTIONAL / MINUS handling, execute queries that have complex OPTIONAL / MINUS elements via the SPARQL interface - with the updated Jena, these should return more quickly / efficiently.

# Interested parties
@VIVO-project/vivo-committers

### CODE REVIEW

**Comment by roflinn** [comment]
In the process of testing.

**Comment by roflinn** [comment]
Got this message when doing a maven install:
-------------------------------------------------------------------------------
Test set: edu.cornell.mannlib.vitro.webapp.controller.api.SparqlUpdateApiTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
nullRdfService(edu.cornell.mannlib.vitro.webapp.controller.api.SparqlUpdateApiTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.jena.query.Dataset.addNamedModel(Ljava/lang/String;Lorg/apache/jena/rdf/model/Model;)V
	at edu.cornell.mannlib.vitro.webapp.controller.api.SparqlUpdateApiTest.setup(SparqlUpdateApiTest.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:168)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by grahamtriggs** [comment]
@roflinn Hi Ralph - how have you set up your test environment?

I updated my fork of Vitro to the latest develop before implementing this change, I am not able to replicate this issue in either my GitHub fork / branch, nor in the TIB fork (where this change has been deployed to two of our implementations).

If you look at the files changed, the RDFServiceDataset (the only implementation of Dataset within the Vitro codebase) changes the addNamedModel() signature to return Dataset rather void, as required by the interfaces and which the error claims is missing.

As far as I can tell, this patch contains the correct change in this regard and it is your test environment that has not applied it correctly.

**Comment by roflinn** [comment]
It was my JDK.  All is well now.

**Comment by awoods** [comment]
@grahamtriggs : Looks like this is good to go, once the Git conflicts have been resolved.

**Comment by grahamtriggs** [comment]
@awoods It was just a single whitespace line from the merge to develop today. Should be clear now.

**Pull request merged**
