### PR TITLE
Added permissions required to upload images

### PR DESCRIPTION
**Pull request by litvinovg**
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3987)**

[VIVO PR](https://github.com/vivo-project/VIVO/pull/3988)

# What does this pull request do?
Added permissions required to upload main images.

# How should this be tested?
* Reproduce the issue
* Test that users with following roles able to upload/remove images: Admin, Curator, Editor, Self editor

# Interested parties
@VIVO-project/vivo-committers

# Reviewers' expertise

Candidates for reviewing this PR should have some of the following expertises:
1. Access control

# Reviewers' report template
## General comment
A reviewer should provide here comments and suggestions for requested changes if any.
## Testing
A reviewer should briefly describe here how it was tested
## Code reviewing
A reviewer should briefly describe here which part was code reviewed

### CODE REVIEW

**Review by balmas — APPROVED** [review]
I can verify that this works. I tested for all role types (admin, curator, editor, self-editor) and confirm that before loading the new property files only the root user was able to add/edit/delete the profile image and after loading the new property files each role type had the ability to add/edit/delete the profileImage (where appropriate for that role/profile combination). Tested mainly in wilma theme but did a quick test with the self-editor role type in the other themes as well).

**Review by balmas — CHANGES_REQUESTED** [review]
Changing status to request changes as noted by @gneissone uploaded images aren't visible by public (non-logged in) users.

**Review by balmas — APPROVED** [review]
Retested and confirm that can now view the profile images as a public (non-logged in user), and image editing capabilities remain correct for all other user role types.

**Review by gneissone — APPROVED** [review]
Tested and appears to work as expected now, thanks!

**Pull request merged**
