### PR TITLE
[VIVO-1458] Upgrade to Jena 3.6.0/Support FROM and FROM NAMED in SDB

### PR DESCRIPTION
**Pull request by gneissone**
**[JIRA Issue: [VIVO-1458]](https://jira.duraspace.org/browse/VIVO-1458)**

* Other Relevant Links (Mailing list discussion, related pull requests, etc.)
https://jira.duraspace.org/browse/VIVO-1373

# What does this pull request do?
Swaps Jena 3.4.0 with the latest and greatest, Jena 3.6.0
What it does NOT do is add new Jena functionality to VIVO (minus the lil' isEmpty method), e.g. TDB2 was released in Jena 3.5.0 but it is not implemented by this pull request

# What's new?
Upgrade to Jena 3.6.0 
Support FROM and FROM NAMED queries in SDB triplestores 

# How should this be tested?
You can reproduce the issue this addresses by attempting to run the below query on an instance running [VIVO 1.10.0 Beta 2 ](https://github.com/vivo-project/VIVO/releases/tag/rel-vivo-1.10.0-beta2) using SDB. You will receive a 500 error with the following message:
`org.apache.jena.sdb.SDBException: Queries with dataset descriptions (FROM/FROM NAMED) not supported`

You can confirm Jena has been upgraded by running this query in a VIVO using SDB
```
SELECT ?s ?p
FROM <http://vitro.mannlib.cornell.edu/default/vitro-kb-2>
WHERE
{
?s ?p ?o .
}
LIMIT 20
```
I have done basic testing on this. VIVO builds and starts, editing the database is possible, and SPARQL queries (including FROM and FROM NAMED) work.

# Additional Notes:
Harvester may need to be updated as well.

# Interested parties
@sarbajitdutta
@fereira

### CODE REVIEW

**Comment by fereira** [comment]
Here are the release notes for Jena 3.7: https://confluence.atlassian.com/jira/jira-3-7-release-notes-184484.html

**Comment by mconlon17** [comment]
Why was the override clause added to RDFServiceDataSet.java?  How does this relate to Jena 3.6?

**Comment by gneissone** [comment]
Since RDFServiceDataset implements Jena's [Dataset interface](https://github.com/apache/jena/blob/master/jena-arq/src/main/java/org/apache/jena/query/Dataset.java) we must implement all of Dataset's methods in RDFServiceDataset. The isEmpty method was added in Jena 3.6.0. [Here](https://github.com/apache/jena/blob/b792e8da1fbe7e397399f2b0803f4e28222c9c3e/jena-arq/src/main/java/org/apache/jena/sparql/core/DatasetImpl.java#L213) is the override in Jena's DatasetImpl.java for comparison.

**Comment by mconlon17** [comment]
Unable to make this work (fails with "from" not supported), but I am unclear on how to build. I am building the develop branch with this pull request.

mvn install -s (didn't work)
mvn clean install -s (didn't work)
blow away vivo-home?  (haven't tried this)
blow away vivo home and maven repository (haven't tried this)

How far do I need to go to insure I get Jena 3.6, not Jena 3.4?

**Comment by gneissone** [comment]
One way is to do a mvn clean install, then search for jena from where you are building.
`find . -name jena*`

If you are still building with 3.4 for some reason, you should see 
./webapp/target/vivo-webapp-1.10.0-SNAPSHOT/WEB-INF/lib/jena-tdb-3.4.0.jar
./webapp/target/vivo-webapp-1.10.0-SNAPSHOT/WEB-INF/lib/jena-arq-3.4.0.jar
...etc 

I would not be surprised if this is what you see. I think subsequent merged pull requests are messing things up. You have checked out the develop branch of VIVO, but are building against Vitro as it was at the time I submitted this PR. Specifically, maven is confused because the version in my PR is 2.0.0-SNAPSHOT but we have since reverted to 1.10.0-SNAPSHOT. 

I suggest running `./update-versions.sh 1.10.0-SNAPSHOT` in the Vitro branch for my PR as an immediate solution. That should solve the build problem. I think the common workflow is to merge subsequent commits into my PR, I'll look into it.

**Comment by gneissone** [comment]
^^^^ done.

**Comment by mconlon17** [comment]
I found 3.4 in the build.  I used update-version.  I rebuilt and found 3.6 in the build.  But when I started VIVO, I got /usr/local/vivo/home/config/applicationSetup.n3' does not define an instance of edu.cornell.mannlib.vitro.webapp.application.ApplicationImpl which indicates some mismatch between VIVO and Vitro branches.  I'm running develop with this pull request.  I can't build a running VIVO with the current develop branches and this pull request.

**Comment by mconlon17** [comment]
I can update versions in Vitro, but when I build VIVO, it reverts to 3.4.  Do we need a corresponding pull request in VIVO?

**Comment by gneissone** [comment]
No, as far as I can tell the dependency is only defined in Vitro. When you build VIVO, make sure Maven isn't reporting any relict 2.0.0-SNAPSHOT parts. The commits I'm building with are e93a8489 (VIVO) and 66c61d8dd (Vitro, with version changes merged). Maybe try updating your Vitro branch to use my latest commit.

**Comment by mconlon17** [comment]
Built.  Runs Sarbajit's query as expected.

**Comment by mjaved495** [comment]
This seems like a completed task. Can it be merged ?

**Pull request merged**
