### PR TITLE
[ i18n sprint ] Move search help page translations to properties

### PR DESCRIPTION
**Pull request by chenejac**
[Companion PR](https://github.com/vivo-project/Vitro-languages/pull/60)
# What does this pull request do? #
Creates language-neutral search help page
# How to test # 
Page to test /searchHelp
# Translations review # 
The sixth advanced tip is missing for Germany, at the moment it is in English
Translations for other languages didn't change, just copied from ftl files to property files.

### CODE REVIEW

**Comment by hauschke** [comment]
The `title="back to results"` in line 6 should be internationalized, too, I think.

**Comment by chenejac** [comment]
> The `title="back to results"` in line 6 should be internationalized, too, I think.

Thanks. I have fixed that.

**Review by litvinovg — APPROVED** [review]
Looks good to me

**Review by bkampe — APPROVED** [review]
Works as expected

**Pull request merged**
