### PR TITLE
Initial step towards decoupling Vitro/checkstyle from Vitro

### PR DESCRIPTION
**Pull request by awoods**
Related to: https://jira.duraspace.org/browse/VIVO-1729

# What does this pull request do?
Decouples the version number of Vitro/checkstyle from the Vitro version number.
A subsequent pull-request should move the Vitro/checkstyle module into its own GitHub repository

# How should this be tested?
The normal maven build should run successfully

# Interested parties
@VIVO-project/vivo-committers

### CODE REVIEW

**Comment by gneissone** [comment]
Pardon my confusion, but does this PR remove all the checkstyle from Vitro at the moment? Is there a replacement at this time? https://github.com/vivo-project/checkstyle looks empty... I only ask because I think this is a good thing and I'm not really sure :)

**Comment by awoods** [comment]
Yes, the pull-request against `vivo-project/checkstyle` should be merged before this change to Vitro.
https://github.com/vivo-project/checkstyle/pull/1

**Comment by gneissone** [comment]
Works as advertised. Note, had to change the checkstyle dependency version to 1.11.0-SNAPSHOT and remove suppressions from a local checkstyle repo (at 1.11.0-SNAPSHOT) to actually test it, since checkstyle version 1.11.0 can be pulled from maven central (and does not currently enforce anything).

**Comment by awoods** [comment]
Thanks for the review, @hudajkhan and @gneissone . Please feel free to merge, and update the JIRA: https://jira.duraspace.org/browse/VIVO-1729

**Pull request merged**
