### PR TITLE
Codestyle

### PR DESCRIPTION
**Pull request by chenejac**
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [3814](https://github.com/vivo-project/VIVO/issues/3814)

[Linked VIVO PR](https://github.com/vivo-project/VIVO/pull/3840)

* Other Relevant Links (Mailing list discussion, related pull requests, etc.)
https://wiki.lyrasis.org/display/VIVO/Code+Style+Guide

# What does this pull request do?
Adding code style into the VIVO/Vitro project

# What's new?
checkstyle.xml added into the Vitro root
checkstyle-suppression.xml added in the Vitro root (empty at the moment)
A wiki page added - https://wiki.lyrasis.org/display/VIVO/Code+Style+Guide
checkstyle.xml file linked in pom.xml file (at the moment configured to be skipped)

# How should this be tested?
Just for reviewing purposes there is commit with code formatted by using this code style at https://github.com/chenejac/Vitro/commit/b214563ef0b0cfe7a5418067539503dc23347104
See instructions for testing in linked VIVO PR

# Interested parties
Tag (@ mention) interested parties or, if unsure, @VIVO-project/vivo-committers

### CODE REVIEW

**Review by wwelling — APPROVED** [review]

**Comment by litvinovg** [comment]
Would it be useful to have configuration file with excluded files? In that case we would be able to create PRs and reduce list of excluded files step by step.

**Comment by chenejac** [comment]
> Would it be useful to have configuration file with excluded files? In that case we would be able to create PRs and reduce list of excluded files step by step.

@litvinovg can you check my last commit in this PR. If that is what you were thinking in your comment, I can apply similar to VIVO PR.

**Review by litvinovg — APPROVED** [review]
Looks good to me.

**Review by litvinovg — CHANGES_REQUESTED** [review]
Let's increase character limit to 120as we discussed in committers call some time ago.

**Review by litvinovg — DISMISSED** [review]

**Review by litvinovg — APPROVED** [review]

**Pull request merged**
